using Routeplanner.Model;
using Routeplanner.Services.Database;
using System.Xml.Linq;

namespace Routeplanner.Services
{
    public class StationTable
    {
        private readonly SQLiteDatabaseService _dbService;

        public StationTable(SQLiteDatabaseService dbService)
        {
            _dbService = dbService;
            SeedStationsAsync();
        }

        public async Task<List<Station>> GetAllStations()
        {
            await _dbService.InitAsync();
            return await _dbService.Database.Table<Station>().ToListAsync();
        }

        public async Task<List<Station>> SearchStationsAsync(string query)
        {
            await _dbService.InitAsync();
            return await _dbService.Database
                                   .Table<Station>()
                                   .Where(s => s.Name.Contains(query))
                                   .ToListAsync();
        }

        public async Task<string> NameToCode(string Name)
        {
            await _dbService.InitAsync();
            var station = await _dbService.Database
                                          .Table<Station>()
                                          .Where(s => s.Name == Name)
                                          .FirstOrDefaultAsync();
            return station?.Code;
        }

        public async Task<string> NamesToCodes(string[] names)
        {
            await _dbService.InitAsync();
            var codes = new List<string>();
            foreach (var Name in names)
            {
                var station = await _dbService.Database
                                              .Table<Station>()
                                              .Where(s => s.Name == Name)
                                              .FirstOrDefaultAsync();
                codes.Add(station?.Code);
            }
            string codesString = string.Join(",", codes);
            return codesString;
        }

        public async Task SeedStationsAsync()
        {
            await _dbService.InitAsync();

            List<Station> stations = new List<Station>
            {
                new Station { Name = "Aalten", Code = "Atn" },
                new Station { Name = "Abcoude", Code = "Ac" },
                new Station { Name = "Akkrum", Code = "Akm" },
                new Station { Name = "Alkmaar Noord", Code = "Amrn" },
                new Station { Name = "Alkmaar", Code = "Amr" },
                new Station { Name = "Almelo de Riet", Code = "Amri" },
                new Station { Name = "Almelo", Code = "Aml" },
                new Station { Name = "Almere Buiten", Code = "Almb" },
                new Station { Name = "Almere Centrum", Code = "Alm" },
                new Station { Name = "Almere Muziekwijk", Code = "Almm" },
                new Station { Name = "Almere Oostvaarders", Code = "Almo" },
                new Station { Name = "Almere Parkwijk", Code = "Almp" },
                new Station { Name = "Almere Poort", Code = "Ampo" },
                new Station { Name = "Alphen aan den Rijn", Code = "Apn" },
                new Station { Name = "Amersfoort Centraal", Code = "Amf" },
                new Station { Name = "Amersfoort Schothorst", Code = "Amfs" },
                new Station { Name = "Amersfoort Vathorst", Code = "Avat" },
                new Station { Name = "Amsterdam Amstel", Code = "Asa" },
                new Station { Name = "Amsterdam Bijlmer ArenA", Code = "Asb" },
                new Station { Name = "Amsterdam Centraal", Code = "Asd" },
                new Station { Name = "Amsterdam Holendrecht", Code = "Ashd" },
                new Station { Name = "Amsterdam Lelylaan", Code = "Asdl" },
                new Station { Name = "Amsterdam Muiderpoort", Code = "Asdm" },
                new Station { Name = "Amsterdam RAI", Code = "Rai" },
                new Station { Name = "Amsterdam Science Park", Code = "Assp" },
                new Station { Name = "Amsterdam Sloterdijk", Code = "Ass" },
                new Station { Name = "Amsterdam Zuid", Code = "Asdz" },
                new Station { Name = "Anna Paulowna", Code = "Ana" },
                new Station { Name = "Apeldoorn De Maten", Code = "Apdm" },
                new Station { Name = "Apeldoorn Osseveld", Code = "Apdo" },
                new Station { Name = "Apeldoorn", Code = "Apd" },
                new Station { Name = "Appingedam", Code = "Apg" },
                new Station { Name = "Arkel", Code = "Akl" },
                new Station { Name = "Arnemuiden", Code = "Arn" },
                new Station { Name = "Arnhem Presikhaaf", Code = "Ahpr" },
                new Station { Name = "Arnhem Centraal", Code = "Ah" },
                new Station { Name = "Arnhem Velperpoort", Code = "Ahp" },
                new Station { Name = "Arnhem Zuid", Code = "Ahz" },
                new Station { Name = "Assen", Code = "Asn" },
                new Station { Name = "Baarn", Code = "Brn" },
                new Station { Name = "Bad Nieuweschans", Code = "Nsch" },
                new Station { Name = "Baflo", Code = "Bf" },
                new Station { Name = "Barendrecht", Code = "Brd" },
                new Station { Name = "Barneveld Centrum", Code = "Bnc" },
                new Station { Name = "Barneveld Noord", Code = "Bnn" },
                new Station { Name = "Barneveld Zuid", Code = "Bnz" },
                new Station { Name = "Bedum", Code = "Bdm" },
                new Station { Name = "Beek-Elsloo", Code = "Bk" },
                new Station { Name = "Beesd", Code = "Bsd" },
                new Station { Name = "Beilen", Code = "Bl" },
                new Station { Name = "Bergen op Zoom", Code = "Bgn" },
                new Station { Name = "Best", Code = "Bet" },
                new Station { Name = "Beverwijk", Code = "Bv" },
                new Station { Name = "Bilthoven", Code = "Bhv" },
                new Station { Name = "Blerick", Code = "Br" },
                new Station { Name = "Bloemendaal", Code = "Bll" },
                new Station { Name = "Bodegraven", Code = "Bdg" },
                new Station { Name = "Borne", Code = "Bn" },
                new Station { Name = "Boskoop", Code = "Bsk" },
                new Station { Name = "Boskoop Snijdelwijk", Code = "Bsks" },
                new Station { Name = "Bovenkarspel Flora", Code = "Bkf" },
                new Station { Name = "Bovenkarspel-Grootebroek", Code = "Bkg" },
                new Station { Name = "Boven Hardinxveld", Code = "Bhdv" },
                new Station { Name = "Boxmeer", Code = "Bmr" },
                new Station { Name = "Boxtel", Code = "Btl" },
                new Station { Name = "Breda Prinsenbeek", Code = "Bdpb" },
                new Station { Name = "Breda", Code = "Bd" },
                new Station { Name = "Breukelen", Code = "Bkl" },
                new Station { Name = "Brummen", Code = "Bmn" },
                new Station { Name = "Buitenpost", Code = "Bp" },
                new Station { Name = "Bunde", Code = "Bde" },
                new Station { Name = "Bunnik", Code = "Bnk" },
                new Station { Name = "Bussum Zuid", Code = "Bsmz" },
                new Station { Name = "Capelle Schollevaar", Code = "Cps" },
                new Station { Name = "Castricum", Code = "Cas" },
                new Station { Name = "Chevremont", Code = "Cvm" },
                new Station { Name = "Coevorden", Code = "Co" },
                new Station { Name = "Cuijk", Code = "Ck" },
                new Station { Name = "Culemborg", Code = "Cl" },
                new Station { Name = "Daarlerveen", Code = "Da" },
                new Station { Name = "Dalen", Code = "Dln" },
                new Station { Name = "Dalfsen", Code = "Dl" },
                new Station { Name = "De Vink", Code = "Dvnk" },
                new Station { Name = "De Westereen", Code = "Dwe" },
                new Station { Name = "Deinum", Code = "Dei" },
                new Station { Name = "Delden", Code = "Ddn" },
                new Station { Name = "Delft", Code = "Dt" },
                new Station { Name = "Delft Campus", Code = "Dtz" },
                new Station { Name = "Delfzijl", Code = "Dz" },
                new Station { Name = "Delfzijl West", Code = "Dzw" },
                new Station { Name = "Den Dolder", Code = "Dld" },
                new Station { Name = "Den Haag Centraal", Code = "Gvc" },
                new Station { Name = "Den Haag Hollands Spoor", Code = "Gv" },
                new Station { Name = "Den Haag Laan van NOI", Code = "Laa" },
                new Station { Name = "Den Haag Mariahoeve", Code = "Gvm" },
                new Station { Name = "Den Haag Moerwijk", Code = "Gvmw" },
                new Station { Name = "Den Haag Ypenburg", Code = "Ypb" },
                new Station { Name = "Den Helder", Code = "Hdr" },
                new Station { Name = "Den Helder Zuid", Code = "Hdrz" },
                new Station { Name = "Deurne", Code = "Dn" },
                new Station { Name = "Deventer Colmschate", Code = "Dvc" },
                new Station { Name = "Deventer", Code = "Dv" },
                new Station { Name = "Didam", Code = "Did" },
                new Station { Name = "Diemen", Code = "Dmn" },
                new Station { Name = "Diemen Zuid", Code = "Dmnz" },
                new Station { Name = "Dieren", Code = "Dr" },
                new Station { Name = "Doetinchem De Huet", Code = "Dtch" },
                new Station { Name = "Doetinchem", Code = "Dtc" },
                new Station { Name = "Dordrecht", Code = "Ddr" },
                new Station { Name = "Dordrecht Stadspolders", Code = "Ddrs" },
                new Station { Name = "Dordrecht Zuid", Code = "Ddzd" },
                new Station { Name = "Driebergen-Zeist", Code = "Db" },
                new Station { Name = "Driehuis", Code = "Dh" },
                new Station { Name = "Dronryp", Code = "Drp" },
                new Station { Name = "Dronten", Code = "Dron" },
                new Station { Name = "Duiven", Code = "Dvn" },
                new Station { Name = "Duivendrecht", Code = "Dvd" },
                new Station { Name = "Echt", Code = "Ec" },
                new Station { Name = "Ede Centrum", Code = "Edc" },
                new Station { Name = "Ede-Wageningen", Code = "Ed" },
                new Station { Name = "Eemshaven", Code = "Eem" },
                new Station { Name = "Eijsden", Code = "Edn" },
                new Station { Name = "Eindhoven Centraal", Code = "Ehv" },
                new Station { Name = "Eindhoven Stadion", Code = "Ehs" },
                new Station { Name = "Eindhoven Strijp-S", Code = "Ehb" },
                new Station { Name = "Elst", Code = "Est" },
                new Station { Name = "Emmen", Code = "Emn" },
                new Station { Name = "Emmen Zuid", Code = "Emnz" },
                new Station { Name = "Enkhuizen", Code = "Ekz" },
                new Station { Name = "Enschede De Eschmarke", Code = "Ese" },
                new Station { Name = "Enschede Kennispark", Code = "Esk" },
                new Station { Name = "Enschede", Code = "Es" },
                new Station { Name = "Ermelo", Code = "Eml" },
                new Station { Name = "Etten-Leur", Code = "Etn" },
                new Station { Name = "Eygelshoven Markt", Code = "Eghm" },
                new Station { Name = "Eygelshoven", Code = "Egh" },
                new Station { Name = "Feanw├ólden", Code = "Fwd" },
                new Station { Name = "Franeker", Code = "Fn" },
                new Station { Name = "Gaanderen", Code = "Gdr" },
                new Station { Name = "Geldermalsen", Code = "Gdm" },
                new Station { Name = "Geldrop", Code = "Gp" },
                new Station { Name = "Geleen Oost", Code = "Gln" },
                new Station { Name = "Geleen-Lutterade", Code = "Lut" },
                new Station { Name = "Gilze-Rijen", Code = "Gz" },
                new Station { Name = "Glanerbrug", Code = "Gbr" },
                new Station { Name = "Goes", Code = "Gs" },
                new Station { Name = "Goor", Code = "Go" },
                new Station { Name = "Gorinchem", Code = "Gr" },
                new Station { Name = "Gouda Goverwelle", Code = "Gdg" },
                new Station { Name = "Gouda", Code = "Gd" },
                new Station { Name = "Gramsbergen", Code = "Gbg" },
                new Station { Name = "Grijpskerk", Code = "Gk" },
                new Station { Name = "Groningen Europapark", Code = "Gerp" },
                new Station { Name = "Groningen Noord", Code = "Gnn" },
                new Station { Name = "Groningen", Code = "Gn" },
                new Station { Name = "Grou-Jirnsum", Code = "Gw" },
                new Station { Name = "Haarlem", Code = "Hlm" },
                new Station { Name = "Haarlem Spaarnwoude", Code = "Hlms" },
                new Station { Name = "Halfweg-Zwanenburg", Code = "Hwzb" },
                new Station { Name = "Hardenberg", Code = "Hdb" },
                new Station { Name = "Harderwijk", Code = "Hd" },
                new Station { Name = "Hardinxveld Blauwe Zoom", Code = "Bzm" },
                new Station { Name = "Hardinxveld-Giessendam", Code = "Gnd" },
                new Station { Name = "Haren (NL)", Code = "Hrn" },
                new Station { Name = "Harlingen Haven", Code = "Hlgh" },
                new Station { Name = "Harlingen", Code = "Hlg" },
                new Station { Name = "Heemskerk", Code = "Hk" },
                new Station { Name = "Heemstede-Aerdenhout", Code = "Had" },
                new Station { Name = "Heerenveen IJsstadion", Code = "Hry" },
                new Station { Name = "Heerenveen", Code = "Hr" },
                new Station { Name = "Heerhugowaard", Code = "Hwd" },
                new Station { Name = "Heerlen", Code = "Hrl" },
                new Station { Name = "Heerlen Woonboulevard", Code = "Hrlw" },
                new Station { Name = "Heeze", Code = "Hz" },
                new Station { Name = "Heiloo", Code = "Hlo" },
                new Station { Name = "Heino", Code = "Hno" },
                new Station { Name = "Helmond Brandevoort", Code = "Hmbv" },
                new Station { Name = "Helmond Brouwhuis", Code = "Hmbh" },
                new Station { Name = "Helmond", Code = "Hm" },
                new Station { Name = "Helmond 't Hout", Code = "Hmh" },
                new Station { Name = "Hemmen-Dodewaard", Code = "Hmn" },
                new Station { Name = "Hengelo Gezondheidspark", Code = "Hglg" },
                new Station { Name = "Hengelo Oost", Code = "Hglo" },
                new Station { Name = "Hengelo", Code = "Hgl" },
                new Station { Name = "Hillegom", Code = "Hil" },
                new Station { Name = "Hilversum Media Park", Code = "Hvsn" },
                new Station { Name = "Hilversum", Code = "Hvs" },
                new Station { Name = "Hilversum Sportpark", Code = "Hvsp" },
                new Station { Name = "Hindeloopen", Code = "Hnp" },
                new Station { Name = "Hoensbroek", Code = "Hb" },
                new Station { Name = "Hoevelaken", Code = "Hvl" },
                new Station { Name = "Hollandsche Rading", Code = "Hor" },
                new Station { Name = "Holten", Code = "Hon" },
                new Station { Name = "Hoofddorp", Code = "Hfd" },
                new Station { Name = "Hoogeveen", Code = "Hgv" },
                new Station { Name = "Hoogezand-Sappemeer", Code = "Hgz" },
                new Station { Name = "Hoogkarspel", Code = "Hks" },
                new Station { Name = "Hoorn Kersenboogerd", Code = "Hnk" },
                new Station { Name = "Hoorn", Code = "Hn" },
                new Station { Name = "Horst-Sevenum", Code = "Hrt" },
                new Station { Name = "Houten Castellum", Code = "Htnc" },
                new Station { Name = "Houten", Code = "Htn" },
                new Station { Name = "Houthem-Sint Gerlach", Code = "Sgl" },
                new Station { Name = "Hurdegaryp", Code = "Hdg" },
                new Station { Name = "IJlst", Code = "IJt" },
                new Station { Name = "Kampen", Code = "Kpn" },
                new Station { Name = "Kampen Zuid", Code = "Kpnz" },
                new Station { Name = "Kapelle-Biezelinge", Code = "Bzl" },
                new Station { Name = "Kerkrade Centrum", Code = "Krd" },
                new Station { Name = "Kesteren", Code = "Ktr" },
                new Station { Name = "Klarenbeek", Code = "Kbk" },
                new Station { Name = "Klimmen-Ransdaal", Code = "Kmr" },
                new Station { Name = "Koog aan de Zaan", Code = "Kbw" },
                new Station { Name = "Koudum-Molkwerum", Code = "Kmw" },
                new Station { Name = "Krabbendijke", Code = "Kbd" },
                new Station { Name = "Krommenie-Assendelft", Code = "Kma" },
                new Station { Name = "Kropswolde", Code = "Kw" },
                new Station { Name = "Kruiningen-Yerseke", Code = "Krg" },
                new Station { Name = "Lage Zwaluwe", Code = "Zlw" },
                new Station { Name = "Landgraaf", Code = "Lg" },
                new Station { Name = "Lansingerland-Zoetermeer", Code = "Llzm" },
                new Station { Name = "Leerdam", Code = "Ldm" },
                new Station { Name = "Leeuwarden Camminghaburen", Code = "Lwc" },
                new Station { Name = "Leeuwarden", Code = "Lw" },
                new Station { Name = "Leiden Centraal", Code = "Ledn" },
                new Station { Name = "Leiden Lammenschans", Code = "Ldl" },
                new Station { Name = "Lelystad Centrum", Code = "Lls" },
                new Station { Name = "Lichtenvoorde-Groenlo", Code = "Ltv" },
                new Station { Name = "Lochem", Code = "Lc" },
                new Station { Name = "Loppersum", Code = "Lp" },
                new Station { Name = "Lunteren", Code = "Ltn" },
                new Station { Name = "Maarheeze", Code = "Mz" },
                new Station { Name = "Maarn", Code = "Mrn" },
                new Station { Name = "Maarssen", Code = "Mas" },
                new Station { Name = "Maastricht Noord", Code = "Mtn" },
                new Station { Name = "Maastricht", Code = "Mt" },
                new Station { Name = "Maastricht Randwyck", Code = "Mtr" },
                new Station { Name = "Mantgum", Code = "Mg" },
                new Station { Name = "Mari├½nberg", Code = "Mrb" },
                new Station { Name = "Martenshoek", Code = "Mth" },
                new Station { Name = "Meerssen", Code = "Mes" },
                new Station { Name = "Meppel", Code = "Mp" },
                new Station { Name = "Middelburg", Code = "Mdb" },
                new Station { Name = "Mook-Molenhoek", Code = "Mmlh" },
                new Station { Name = "Naarden-Bussum", Code = "Ndb" },
                new Station { Name = "Nieuw Amsterdam", Code = "Na" },
                new Station { Name = "Nieuwerkerk aan den IJssel", Code = "Nwk" },
                new Station { Name = "Nieuw-Vennep", Code = "Nvp" },
                new Station { Name = "Nijkerk", Code = "Nkk" },
                new Station { Name = "Nijmegen Dukenburg", Code = "Nmd" },
                new Station { Name = "Nijmegen Goffert", Code = "Nmgo" },
                new Station { Name = "Nijmegen Heyendaal", Code = "Nmh" },
                new Station { Name = "Nijmegen Lent", Code = "Nml" },
                new Station { Name = "Nijmegen", Code = "Nm" },
                new Station { Name = "Nijverdal", Code = "Nvd" },
                new Station { Name = "Nunspeet", Code = "Ns" },
                new Station { Name = "Nuth", Code = "Nh" },
                new Station { Name = "Obdam", Code = "Obd" },
                new Station { Name = "Oisterwijk", Code = "Ot" },
                new Station { Name = "Oldenzaal", Code = "Odz" },
                new Station { Name = "Olst", Code = "Ost" },
                new Station { Name = "Ommen", Code = "Omn" },
                new Station { Name = "Oosterbeek", Code = "Otb" },
                new Station { Name = "Opheusden", Code = "Op" },
                new Station { Name = "Oss", Code = "O" },
                new Station { Name = "Oss West", Code = "Ow" },
                new Station { Name = "Oudenbosch", Code = "Odb" },
                new Station { Name = "Overveen", Code = "Ovn" },
                new Station { Name = "Purmerend Overwhere", Code = "Pmo" },
                new Station { Name = "Purmerend", Code = "Pmr" },
                new Station { Name = "Purmerend Weidevenne", Code = "Pmw" },
                new Station { Name = "Putten", Code = "Pt" },
                new Station { Name = "Raalte", Code = "Rat" },
                new Station { Name = "Ravenstein", Code = "Rvs" },
                new Station { Name = "Reuver", Code = "Rv" },
                new Station { Name = "Rheden", Code = "Rh" },
                new Station { Name = "Rhenen", Code = "Rhn" },
                new Station { Name = "Rijssen", Code = "Rsn" },
                new Station { Name = "Rijswijk", Code = "Rsw" },
                new Station { Name = "Rilland-Bath", Code = "Rb" },
                new Station { Name = "Roermond", Code = "Rm" },
                new Station { Name = "Roodeschool", Code = "Rd" },
                new Station { Name = "Roosendaal", Code = "Rsd" },
                new Station { Name = "Rosmalen", Code = "Rs" },
                new Station { Name = "Rotterdam Alexander", Code = "Rta" },
                new Station { Name = "Rotterdam Blaak", Code = "Rtb" },
                new Station { Name = "Rotterdam Centraal", Code = "Rtd" },
                new Station { Name = "Rotterdam Lombardijen", Code = "Rlb" },
                new Station { Name = "Rotterdam Noord", Code = "Rtn" },
                new Station { Name = "Rotterdam Stadion", Code = "Rtst" },
                new Station { Name = "Rotterdam Zuid", Code = "Rtz" },
                new Station { Name = "Ruurlo", Code = "Rl" },
                new Station { Name = "Santpoort Noord", Code = "Sptn" },
                new Station { Name = "Santpoort Zuid", Code = "Sptz" },
                new Station { Name = "Sassenheim", Code = "Ssh" },
                new Station { Name = "Sauwerd", Code = "Swd" },
                new Station { Name = "Schagen", Code = "Sgn" },
                new Station { Name = "Scheemda", Code = "Sda" },
                new Station { Name = "Schiedam Centrum", Code = "Sdm" },
                new Station { Name = "Schin op Geul", Code = "Sog" },
                new Station { Name = "Schinnen", Code = "Sn" },
                new Station { Name = "Schiphol", Code = "Shl" },
                new Station { Name = "'s-Hertogenbosch Oost", Code = "Hto" },
                new Station { Name = "'s-Hertogenbosch", Code = "Ht" },
                new Station { Name = "Sittard", Code = "Std" },
                new Station { Name = "Sliedrecht Baanhoek", Code = "Sdtb" },
                new Station { Name = "Sliedrecht", Code = "Sdt" },
                new Station { Name = "Sneek Noord", Code = "Sknd" },
                new Station { Name = "Sneek", Code = "Sk" },
                new Station { Name = "Soest (Netherlands)", Code = "St" },
                new Station { Name = "Soest Zuid", Code = "Stz" },
                new Station { Name = "Soestdijk", Code = "Sd" },
                new Station { Name = "Spaubeek", Code = "Sbk" },
                new Station { Name = "Stavoren", Code = "Stv" },
                new Station { Name = "Stedum", Code = "Stm" },
                new Station { Name = "Steenwijk", Code = "Swk" },
                new Station { Name = "Susteren", Code = "Srn" },
                new Station { Name = "Swalmen", Code = "Sm" },
                new Station { Name = "'t Harde", Code = "Hde" },
                new Station { Name = "Tegelen", Code = "Tg" },
                new Station { Name = "Terborg", Code = "Tbg" },
                new Station { Name = "Tiel Passewaaij", Code = "Tpsw" },
                new Station { Name = "Tiel", Code = "Tl" },
                new Station { Name = "Tilburg", Code = "Tb" },
                new Station { Name = "Tilburg Reeshof", Code = "Tbr" },
                new Station { Name = "Tilburg Universiteit", Code = "Tbu" },
                new Station { Name = "Twello", Code = "Twl" },
                new Station { Name = "Uitgeest", Code = "Utg" },
                new Station { Name = "Uithuizen", Code = "Uhz" },
                new Station { Name = "Uithuizermeeden", Code = "Uhm" },
                new Station { Name = "Usquert", Code = "Ust" },
                new Station { Name = "Utrecht Centraal", Code = "Ut" },
                new Station { Name = "Utrecht Leidsche Rijn", Code = "Utlr" },
                new Station { Name = "Utrecht Lunetten", Code = "Utl" },
                new Station { Name = "Utrecht Maliebaan", Code = "Utm" },
                new Station { Name = "Utrecht Overvecht", Code = "Uto" },
                new Station { Name = "Utrecht Terwijde", Code = "Utt" },
                new Station { Name = "Utrecht Vaartsche Rijn", Code = "Utvr" },
                new Station { Name = "Utrecht Zuilen", Code = "Utzl" },
                new Station { Name = "Valkenburg", Code = "Vk" },
                new Station { Name = "Varsseveld", Code = "Vsv" },
                new Station { Name = "Veendam", Code = "Vdm" },
                new Station { Name = "Veenendaal Centrum", Code = "Vndc" },
                new Station { Name = "Veenendaal West", Code = "Vndw" },
                new Station { Name = "Veenendaal-De Klomp", Code = "Klp" },
                new Station { Name = "Velp", Code = "Vp" },
                new Station { Name = "Venlo", Code = "Vl" },
                new Station { Name = "Venray", Code = "Vry" },
                new Station { Name = "Vierlingsbeek", Code = "Vlb" },
                new Station { Name = "Vleuten", Code = "Vtn" },
                new Station { Name = "Vlissingen", Code = "Vs" },
                new Station { Name = "Vlissingen Souburg", Code = "Vss" },
                new Station { Name = "Voerendaal", Code = "Vdl" },
                new Station { Name = "Voorburg", Code = "Vb" },
                new Station { Name = "Voorhout", Code = "Vh" },
                new Station { Name = "Voorschoten", Code = "Vst" },
                new Station { Name = "Voorst-Empe", Code = "Vem" },
                new Station { Name = "Vorden", Code = "Vd" },
                new Station { Name = "Vriezenveen", Code = "Vz" },
                new Station { Name = "Vroomshoop", Code = "Vhp" },
                new Station { Name = "Vught", Code = "Vg" },
                new Station { Name = "Waddinxveen Noord", Code = "Wadn" },
                new Station { Name = "Waddinxveen", Code = "Wad" },
                new Station { Name = "Waddinxveen Triangel", Code = "Wadt" },
                new Station { Name = "Warffum", Code = "Wfm" },
                new Station { Name = "Weert", Code = "Wt" },
                new Station { Name = "Weesp", Code = "Wp" },
                new Station { Name = "Wehl", Code = "Wl" },
                new Station { Name = "Westervoort", Code = "Wtv" },
                new Station { Name = "Wezep", Code = "Wz" },
                new Station { Name = "Wierden", Code = "Wdn" },
                new Station { Name = "Wijchen", Code = "Wc" },
                new Station { Name = "Wijhe", Code = "Wh" },
                new Station { Name = "Winschoten", Code = "Ws" },
                new Station { Name = "Winsum", Code = "Wsm" },
                new Station { Name = "Winterswijk", Code = "Ww" },
                new Station { Name = "Winterswijk West", Code = "Www" },
                new Station { Name = "Woerden", Code = "Wd" },
                new Station { Name = "Wolfheze", Code = "Wf" },
                new Station { Name = "Wolvega", Code = "Wv" },
                new Station { Name = "Workum", Code = "Wk" },
                new Station { Name = "Wormerveer", Code = "Wm" },
                new Station { Name = "Zaandam Kogerveld", Code = "Zdk" },
                new Station { Name = "Zaandam", Code = "Zd" },
                new Station { Name = "Zaandijk Zaanse Schans", Code = "Kzd" },
                new Station { Name = "Zaltbommel", Code = "Zbm" },
                new Station { Name = "Zandvoort aan Zee", Code = "Zvt" },
                new Station { Name = "Zetten-Andelst", Code = "Za" },
                new Station { Name = "Zevenaar", Code = "Zv" },
                new Station { Name = "Zevenbergen", Code = "Zvb" },
                new Station { Name = "Zoetermeer Oost", Code = "Ztmo" },
                new Station { Name = "Zoetermeer", Code = "Ztm" },
                new Station { Name = "Zuidbroek", Code = "Zb" },
                new Station { Name = "Zuidhorn", Code = "Zh" },
                new Station { Name = "Zutphen", Code = "Zp" },
                new Station { Name = "Zwijndrecht", Code = "Zwd" },
                new Station { Name = "Zwolle", Code = "Zl" },
                new Station { Name = "Zwolle Stadshagen", Code = "Zlsh" }
            };

            foreach (var station in stations)
            {
                await _dbService.Database.InsertAsync(station);
            }
        }
    }
}