using Routeplanner.Model;
using SQLite;

namespace Routeplanner.Services
{
    public class SqliteMonkeyService : ITripService
    {
        SQLiteAsyncConnection Database;

        public SqliteMonkeyService()
        {
        }

        public async Task<List<Station>> GetStations()
        {
            await Init();
            return await Database.Table<Station>().ToListAsync();
        }

        async Task Init()
        {
            if (Database is not null)
                return;

            Database = new SQLiteAsyncConnection(Constants.DatabasePath, Constants.Flags);
            var result = await Database.CreateTableAsync<Station>();

            await SeedDatabase();
        }

        async Task SeedDatabase()
        {
            List<Station> stations = new List<Station>()
        {
            new Station { name = "Aalten", code = "Atn" },
            new Station { name = "Abcoude", code = "Ac" },
            new Station { name = "Akkrum", code = "Akm" },
            new Station { name = "Alkmaar Noord", code = "Amrn" },
            new Station { name = "Alkmaar", code = "Amr" },
            new Station { name = "Almelo de Riet", code = "Amri" },
            new Station { name = "Almelo", code = "Aml" },
            new Station { name = "Almere Buiten", code = "Almb" },
            new Station { name = "Almere Centrum", code = "Alm" },
            new Station { name = "Almere Muziekwijk", code = "Almm" },
            new Station { name = "Almere Oostvaarders", code = "Almo" },
            new Station { name = "Almere Parkwijk", code = "Almp" },
            new Station { name = "Almere Poort", code = "Ampo" },
            new Station { name = "Alphen aan den Rijn", code = "Apn" },
            new Station { name = "Amersfoort Centraal", code = "Amf" },
            new Station { name = "Amersfoort Schothorst", code = "Amfs" },
            new Station { name = "Amersfoort Vathorst", code = "Avat" },
            new Station { name = "Amsterdam Amstel", code = "Asa" },
            new Station { name = "Amsterdam Arena", code = "Asdar" },
            new Station { name = "Amsterdam Bijlmer ArenA", code = "Asb" },
            new Station { name = "Amsterdam Centraal", code = "Asd" },
            new Station { name = "Amsterdam Holendrecht", code = "Ashd" },
            new Station { name = "Amsterdam Lelylaan", code = "Asdl" },
            new Station { name = "Amsterdam Muiderpoort", code = "Asdm" },
            new Station { name = "Amsterdam RAI", code = "Rai" },
            new Station { name = "Amsterdam Science Park", code = "Assp" },
            new Station { name = "Amsterdam Sloterdijk", code = "Ass" },
            new Station { name = "Amsterdam Zuid", code = "Asdz" },
            new Station { name = "Anna Paulowna", code = "Ana" },
            new Station { name = "Apeldoorn De Maten", code = "Apdm" },
            new Station { name = "Apeldoorn Osseveld", code = "Apdo" },
            new Station { name = "Apeldoorn", code = "Apd" },
            new Station { name = "Appingedam", code = "Apg" },
            new Station { name = "Arkel", code = "Akl" },
            new Station { name = "Arnemuiden", code = "Arn" },
            new Station { name = "Arnhem Presikhaaf", code = "Ahpr" },
            new Station { name = "Arnhem Centraal", code = "Ah" },
            new Station { name = "Arnhem Velperpoort", code = "Ahp" },
            new Station { name = "Arnhem Zuid", code = "Ahz" },
            new Station { name = "Assen", code = "Asn" },
            new Station { name = "Baarn", code = "Brn" },
            new Station { name = "Bad Nieuweschans", code = "Nsch" },
            new Station { name = "Baflo", code = "Bf" },
            new Station { name = "Barendrecht", code = "Brd" },
            new Station { name = "Barneveld Centrum", code = "Bnc" },
            new Station { name = "Barneveld Noord", code = "Bnn" },
            new Station { name = "Barneveld Zuid", code = "Bnz" },
            new Station { name = "Bedum", code = "Bdm" },
            new Station { name = "Beek-Elsloo", code = "Bk" },
            new Station { name = "Beesd", code = "Bsd" },
            new Station { name = "Beilen", code = "Bl" },
            new Station { name = "Bergen op Zoom", code = "Bgn" },
            new Station { name = "Best", code = "Bet" },
            new Station { name = "Beverwijk", code = "Bv" },
            new Station { name = "Bilthoven", code = "Bhv" },
            new Station { name = "Blerick", code = "Br" },
            new Station { name = "Bloemendaal", code = "Bll" },
            new Station { name = "Bodegraven", code = "Bdg" },
            new Station { name = "Borne", code = "Bn" },
            new Station { name = "Boskoop", code = "Bsk" },
            new Station { name = "Boskoop Snijdelwijk", code = "Bsks" },
            new Station { name = "Bovenkarspel Flora", code = "Bkf" },
            new Station { name = "Bovenkarspel-Grootebroek", code = "Bkg" },
            new Station { name = "Boven Hardinxveld", code = "Bhdv" },
            new Station { name = "Boxmeer", code = "Bmr" },
            new Station { name = "Boxtel", code = "Btl" },
            new Station { name = "Breda Prinsenbeek", code = "Bdpb" },
            new Station { name = "Breda", code = "Bd" },
            new Station { name = "Breukelen", code = "Bkl" },
            new Station { name = "Brummen", code = "Bmn" },
            new Station { name = "Buitenpost", code = "Bp" },
            new Station { name = "Bunde", code = "Bde" },
            new Station { name = "Bunnik", code = "Bnk" },
            new Station { name = "Bussum Zuid", code = "Bsmz" },
            new Station { name = "Capelle Schollevaar", code = "Cps" },
            new Station { name = "Castricum", code = "Cas" },
            new Station { name = "Chevremont", code = "Cvm" },
            new Station { name = "Coevorden", code = "Co" },
            new Station { name = "Cuijk", code = "Ck" },
            new Station { name = "Culemborg", code = "Cl" },
            new Station { name = "Daarlerveen", code = "Da" },
            new Station { name = "Dalen", code = "Dln" },
            new Station { name = "Dalfsen", code = "Dl" },
            new Station { name = "De Vink", code = "Dvnk" },
            new Station { name = "De Westereen", code = "Dwe" },
            new Station { name = "Deinum", code = "Dei" },
            new Station { name = "Delden", code = "Ddn" },
            new Station { name = "Delft", code = "Dt" },
            new Station { name = "Delft Campus", code = "Dtz" },
            new Station { name = "Delfzijl", code = "Dz" },
            new Station { name = "Delfzijl West", code = "Dzw" },
            new Station { name = "Den Dolder", code = "Dld" },
            new Station { name = "Den Haag Centraal", code = "Gvc" },
            new Station { name = "Den Haag Hollands Spoor", code = "Gv" },
            new Station { name = "Den Haag Laan van NOI", code = "Laa" },
            new Station { name = "Den Haag Mariahoeve", code = "Gvm" },
            new Station { name = "Den Haag Moerwijk", code = "Gvmw" },
            new Station { name = "Den Haag Ypenburg", code = "Ypb" },
            new Station { name = "Den Helder", code = "Hdr" },
            new Station { name = "Den Helder Zuid", code = "Hdrz" },
            new Station { name = "Deurne", code = "Dn" },
            new Station { name = "Deventer Colmschate", code = "Dvc" },
            new Station { name = "Deventer", code = "Dv" },
            new Station { name = "Didam", code = "Did" },
            new Station { name = "Diemen", code = "Dmn" },
            new Station { name = "Diemen Zuid", code = "Dmnz" },
            new Station { name = "Dieren", code = "Dr" },
            new Station { name = "Doetinchem De Huet", code = "Dtch" },
            new Station { name = "Doetinchem", code = "Dtc" },
            new Station { name = "Dordrecht", code = "Ddr" },
            new Station { name = "Dordrecht Stadspolders", code = "Ddrs" },
            new Station { name = "Dordrecht Zuid", code = "Ddzd" },
            new Station { name = "Driebergen-Zeist", code = "Db" },
            new Station { name = "Driehuis", code = "Dh" },
            new Station { name = "Dronryp", code = "Drp" },
            new Station { name = "Dronten", code = "Dron" },
            new Station { name = "Duiven", code = "Dvn" },
            new Station { name = "Duivendrecht", code = "Dvd" },
            new Station { name = "Echt", code = "Ec" },
            new Station { name = "Ede Centrum", code = "Edc" },
            new Station { name = "Ede-Wageningen", code = "Ed" },
            new Station { name = "Eemshaven", code = "Eem" },
            new Station { name = "Eijsden", code = "Edn" },
            new Station { name = "Eindhoven Centraal", code = "Ehv" },
            new Station { name = "Eindhoven Stadion", code = "Ehs" },
            new Station { name = "Eindhoven Strijp-S", code = "Ehb" },
            new Station { name = "Elst", code = "Est" },
            new Station { name = "Emmen", code = "Emn" },
            new Station { name = "Emmen Zuid", code = "Emnz" },
            new Station { name = "Enkhuizen", code = "Ekz" },
            new Station { name = "Enschede De Eschmarke", code = "Ese" },
            new Station { name = "Enschede Kennispark", code = "Esk" },
            new Station { name = "Enschede", code = "Es" },
            new Station { name = "Ermelo", code = "Eml" },
            new Station { name = "Etten-Leur", code = "Etn" },
            new Station { name = "Eygelshoven Markt", code = "Eghm" },
            new Station { name = "Eygelshoven", code = "Egh" },
            new Station { name = "Feanwâlden", code = "Fwd" },
            new Station { name = "Franeker", code = "Fn" },
            new Station { name = "Gaanderen", code = "Gdr" },
            new Station { name = "Geldermalsen", code = "Gdm" },
            new Station { name = "Geldrop", code = "Gp" },
            new Station { name = "Geleen Oost", code = "Gln" },
            new Station { name = "Geleen-Lutterade", code = "Lut" },
            new Station { name = "Gilze-Rijen", code = "Gz" },
            new Station { name = "Glanerbrug", code = "Gbr" },
            new Station { name = "Goes", code = "Gs" },
            new Station { name = "Goor", code = "Go" },
            new Station { name = "Gorinchem", code = "Gr" },
            new Station { name = "Gouda Goverwelle", code = "Gdg" },
            new Station { name = "Gouda", code = "Gd" },
            new Station { name = "Gramsbergen", code = "Gbg" },
            new Station { name = "Grijpskerk", code = "Gk" },
            new Station { name = "Groningen Europapark", code = "Gerp" },
            new Station { name = "Groningen Noord", code = "Gnn" },
            new Station { name = "Groningen", code = "Gn" },
            new Station { name = "Grou-Jirnsum", code = "Gw" },
            new Station { name = "Haarlem", code = "Hlm" },
            new Station { name = "Haarlem Spaarnwoude", code = "Hlms" },
            new Station { name = "Halfweg-Zwanenburg", code = "Hwzb" },
            new Station { name = "Hardenberg", code = "Hdb" },
            new Station { name = "Harderwijk", code = "Hd" },
            new Station { name = "Hardinxveld Blauwe Zoom", code = "Bzm" },
            new Station { name = "Hardinxveld-Giessendam", code = "Gnd" },
            new Station { name = "Haren (NL)", code = "Hrn" },
            new Station { name = "Harlingen Haven", code = "Hlgh" },
            new Station { name = "Harlingen", code = "Hlg" },
            new Station { name = "Heemskerk", code = "Hk" },
            new Station { name = "Heemstede-Aerdenhout", code = "Had" },
            new Station { name = "Heerenveen IJsstadion", code = "Hry" },
            new Station { name = "Heerenveen", code = "Hr" },
            new Station { name = "Heerhugowaard", code = "Hwd" },
            new Station { name = "Heerlen", code = "Hrl" },
            new Station { name = "Heerlen Woonboulevard", code = "Hrlw" },
            new Station { name = "Heeze", code = "Hz" },
            new Station { name = "Heiloo", code = "Hlo" },
            new Station { name = "Heino", code = "Hno" },
            new Station { name = "Helmond Brandevoort", code = "Hmbv" },
            new Station { name = "Helmond Brouwhuis", code = "Hmbh" },
            new Station { name = "Helmond", code = "Hm" },
            new Station { name = "Helmond 't Hout", code = "Hmh" },
            new Station { name = "Hemmen-Dodewaard", code = "Hmn" },
            new Station { name = "Hengelo Gezondheidspark", code = "Hglg" },
            new Station { name = "Hengelo Oost", code = "Hglo" },
            new Station { name = "Hengelo", code = "Hgl" },
            new Station { name = "Hillegom", code = "Hil" },
            new Station { name = "Hilversum Media Park", code = "Hvsn" },
            new Station { name = "Hilversum", code = "Hvs" },
            new Station { name = "Hilversum Sportpark", code = "Hvsp" },
            new Station { name = "Hindeloopen", code = "Hnp" },
            new Station { name = "Hoensbroek", code = "Hb" },
            new Station { name = "Hoevelaken", code = "Hvl" },
            new Station { name = "Hollandsche Rading", code = "Hor" },
            new Station { name = "Holten", code = "Hon" },
            new Station { name = "Hoofddorp", code = "Hfd" },
            new Station { name = "Hoogeveen", code = "Hgv" },
            new Station { name = "Hoogezand-Sappemeer", code = "Hgz" },
            new Station { name = "Hoogkarspel", code = "Hks" },
            new Station { name = "Hoorn Kersenboogerd", code = "Hnk" },
            new Station { name = "Hoorn", code = "Hn" },
            new Station { name = "Horst-Sevenum", code = "Hrt" },
            new Station { name = "Houten Castellum", code = "Htnc" },
            new Station { name = "Houten", code = "Htn" },
            new Station { name = "Houthem-Sint Gerlach", code = "Sgl" },
            new Station { name = "Hurdegaryp", code = "Hdg" },
            new Station { name = "IJlst", code = "IJt" },
            new Station { name = "Kampen", code = "Kpn" },
            new Station { name = "Kampen Zuid", code = "Kpnz" },
            new Station { name = "Kapelle-Biezelinge", code = "Bzl" },
            new Station { name = "Kerkrade Centrum", code = "Krd" },
            new Station { name = "Kesteren", code = "Ktr" },
            new Station { name = "Klarenbeek", code = "Kbk" },
            new Station { name = "Klimmen-Ransdaal", code = "Kmr" },
            new Station { name = "Koog aan de Zaan", code = "Kbw" },
            new Station { name = "Koudum-Molkwerum", code = "Kmw" },
            new Station { name = "Krabbendijke", code = "Kbd" },
            new Station { name = "Krommenie-Assendelft", code = "Kma" },
            new Station { name = "Kropswolde", code = "Kw" },
            new Station { name = "Kruiningen-Yerseke", code = "Krg" },
            new Station { name = "Lage Zwaluwe", code = "Zlw" },
            new Station { name = "Landgraaf", code = "Lg" },
            new Station { name = "Lansingerland-Zoetermeer", code = "Llzm" },
            new Station { name = "Leerdam", code = "Ldm" },
            new Station { name = "Leeuwarden Camminghaburen", code = "Lwc" },
            new Station { name = "Leeuwarden", code = "Lw" },
            new Station { name = "Leiden Centraal", code = "Ledn" },
            new Station { name = "Leiden Lammenschans", code = "Ldl" },
            new Station { name = "Lelystad Centrum", code = "Lls" },
            new Station { name = "Lichtenvoorde-Groenlo", code = "Ltv" },
            new Station { name = "Lochem", code = "Lc" },
            new Station { name = "Loppersum", code = "Lp" },
            new Station { name = "Lunteren", code = "Ltn" },
            new Station { name = "Maarheeze", code = "Mz" },
            new Station { name = "Maarn", code = "Mrn" },
            new Station { name = "Maarssen", code = "Mas" },
            new Station { name = "Maastricht Noord", code = "Mtn" },
            new Station { name = "Maastricht", code = "Mt" },
            new Station { name = "Maastricht Randwyck", code = "Mtr" },
            new Station { name = "Mantgum", code = "Mg" },
            new Station { name = "Mariënberg", code = "Mrb" },
            new Station { name = "Martenshoek", code = "Mth" },
            new Station { name = "Meerssen", code = "Mes" },
            new Station { name = "Meppel", code = "Mp" },
            new Station { name = "Middelburg", code = "Mdb" },
            new Station { name = "Mook-Molenhoek", code = "Mmlh" },
            new Station { name = "Naarden-Bussum", code = "Ndb" },
            new Station { name = "Nieuw Amsterdam", code = "Na" },
            new Station { name = "Nieuwerkerk aan den IJssel", code = "Nwk" },
            new Station { name = "Nieuw-Vennep", code = "Nvp" },
            new Station { name = "Nijkerk", code = "Nkk" },
            new Station { name = "Nijmegen Dukenburg", code = "Nmd" },
            new Station { name = "Nijmegen Goffert", code = "Nmgo" },
            new Station { name = "Nijmegen Heyendaal", code = "Nmh" },
            new Station { name = "Nijmegen Lent", code = "Nml" },
            new Station { name = "Nijmegen", code = "Nm" },
            new Station { name = "Nijverdal", code = "Nvd" },
            new Station { name = "Nunspeet", code = "Ns" },
            new Station { name = "Nuth", code = "Nh" },
            new Station { name = "Obdam", code = "Obd" },
            new Station { name = "Oisterwijk", code = "Ot" },
            new Station { name = "Oldenzaal", code = "Odz" },
            new Station { name = "Olst", code = "Ost" },
            new Station { name = "Ommen", code = "Omn" },
            new Station { name = "Oosterbeek", code = "Otb" },
            new Station { name = "Opheusden", code = "Op" },
            new Station { name = "Oss", code = "O" },
            new Station { name = "Oss West", code = "Ow" },
            new Station { name = "Oudenbosch", code = "Odb" },
            new Station { name = "Overveen", code = "Ovn" },
            new Station { name = "Purmerend Overwhere", code = "Pmo" },
            new Station { name = "Purmerend", code = "Pmr" },
            new Station { name = "Purmerend Weidevenne", code = "Pmw" },
            new Station { name = "Putten", code = "Pt" },
            new Station { name = "Raalte", code = "Rat" },
            new Station { name = "Ravenstein", code = "Rvs" },
            new Station { name = "Reuver", code = "Rv" },
            new Station { name = "Rheden", code = "Rh" },
            new Station { name = "Rhenen", code = "Rhn" },
            new Station { name = "Rijssen", code = "Rsn" },
            new Station { name = "Rijswijk", code = "Rsw" },
            new Station { name = "Rilland-Bath", code = "Rb" },
            new Station { name = "Roermond", code = "Rm" },
            new Station { name = "Roodeschool", code = "Rd" },
            new Station { name = "Roosendaal", code = "Rsd" },
            new Station { name = "Rosmalen", code = "Rs" },
            new Station { name = "Rotterdam Alexander", code = "Rta" },
            new Station { name = "Rotterdam Blaak", code = "Rtb" },
            new Station { name = "Rotterdam Centraal", code = "Rtd" },
            new Station { name = "Rotterdam Lombardijen", code = "Rlb" },
            new Station { name = "Rotterdam Noord", code = "Rtn" },
            new Station { name = "Rotterdam Stadion", code = "Rtst" },
            new Station { name = "Rotterdam Zuid", code = "Rtz" },
            new Station { name = "Ruurlo", code = "Rl" },
            new Station { name = "Santpoort Noord", code = "Sptn" },
            new Station { name = "Santpoort Zuid", code = "Sptz" },
            new Station { name = "Sassenheim", code = "Ssh" },
            new Station { name = "Sauwerd", code = "Swd" },
            new Station { name = "Schagen", code = "Sgn" },
            new Station { name = "Scheemda", code = "Sda" },
            new Station { name = "Schiedam Centrum", code = "Sdm" },
            new Station { name = "Schin op Geul", code = "Sog" },
            new Station { name = "Schinnen", code = "Sn" },
            new Station { name = "Schiphol", code = "Shl" },
            new Station { name = "'s-Hertogenbosch Oost", code = "Hto" },
            new Station { name = "'s-Hertogenbosch", code = "Ht" },
            new Station { name = "Sittard", code = "Std" },
            new Station { name = "Sliedrecht Baanhoek", code = "Sdtb" },
            new Station { name = "Sliedrecht", code = "Sdt" },
            new Station { name = "Sneek Noord", code = "Sknd" },
            new Station { name = "Sneek", code = "Sk" },
            new Station { name = "Soest (Netherlands)", code = "St" },
            new Station { name = "Soest Zuid", code = "Stz" },
            new Station { name = "Soestdijk", code = "Sd" },
            new Station { name = "Spaubeek", code = "Sbk" },
            new Station { name = "Stavoren", code = "Stv" },
            new Station { name = "Stedum", code = "Stm" },
            new Station { name = "Steenwijk", code = "Swk" },
            new Station { name = "Susteren", code = "Srn" },
            new Station { name = "Swalmen", code = "Sm" },
            new Station { name = "'t Harde", code = "Hde" },
            new Station { name = "Tegelen", code = "Tg" },
            new Station { name = "Terborg", code = "Tbg" },
            new Station { name = "Tiel Passewaaij", code = "Tpsw" },
            new Station { name = "Tiel", code = "Tl" },
            new Station { name = "Tilburg", code = "Tb" },
            new Station { name = "Tilburg Reeshof", code = "Tbr" },
            new Station { name = "Tilburg Universiteit", code = "Tbu" },
            new Station { name = "Twello", code = "Twl" },
            new Station { name = "Uitgeest", code = "Utg" },
            new Station { name = "Uithuizen", code = "Uhz" },
            new Station { name = "Uithuizermeeden", code = "Uhm" },
            new Station { name = "Usquert", code = "Ust" },
            new Station { name = "Utrecht Centraal", code = "Ut" },
            new Station { name = "Utrecht Leidsche Rijn", code = "Utlr" },
            new Station { name = "Utrecht Lunetten", code = "Utl" },
            new Station { name = "Utrecht Maliebaan", code = "Utm" },
            new Station { name = "Utrecht Overvecht", code = "Uto" },
            new Station { name = "Utrecht Terwijde", code = "Utt" },
            new Station { name = "Utrecht Vaartsche Rijn", code = "Utvr" },
            new Station { name = "Utrecht Zuilen", code = "Utzl" },
            new Station { name = "Valkenburg", code = "Vk" },
            new Station { name = "Varsseveld", code = "Vsv" },
            new Station { name = "Veendam", code = "Vdm" },
            new Station { name = "Veenendaal Centrum", code = "Vndc" },
            new Station { name = "Veenendaal West", code = "Vndw" },
            new Station { name = "Veenendaal-De Klomp", code = "Klp" },
            new Station { name = "Velp", code = "Vp" },
            new Station { name = "Venlo", code = "Vl" },
            new Station { name = "Venray", code = "Vry" },
            new Station { name = "Vierlingsbeek", code = "Vlb" },
            new Station { name = "Vleuten", code = "Vtn" },
            new Station { name = "Vlissingen", code = "Vs" },
            new Station { name = "Vlissingen Souburg", code = "Vss" },
            new Station { name = "Voerendaal", code = "Vdl" },
            new Station { name = "Voorburg", code = "Vb" },
            new Station { name = "Voorhout", code = "Vh" },
            new Station { name = "Voorschoten", code = "Vst" },
            new Station { name = "Voorst-Empe", code = "Vem" },
            new Station { name = "Vorden", code = "Vd" },
            new Station { name = "Vriezenveen", code = "Vz" },
            new Station { name = "Vroomshoop", code = "Vhp" },
            new Station { name = "Vught", code = "Vg" },
            new Station { name = "Waddinxveen Noord", code = "Wadn" },
            new Station { name = "Waddinxveen", code = "Wad" },
            new Station { name = "Waddinxveen Triangel", code = "Wadt" },
            new Station { name = "Warffum", code = "Wfm" },
            new Station { name = "Weert", code = "Wt" },
            new Station { name = "Weesp", code = "Wp" },
            new Station { name = "Wehl", code = "Wl" },
            new Station { name = "Westervoort", code = "Wtv" },
            new Station { name = "Wezep", code = "Wz" },
            new Station { name = "Wierden", code = "Wdn" },
            new Station { name = "Wijchen", code = "Wc" },
            new Station { name = "Wijhe", code = "Wh" },
            new Station { name = "Winschoten", code = "Ws" },
            new Station { name = "Winsum", code = "Wsm" },
            new Station { name = "Winterswijk", code = "Ww" },
            new Station { name = "Winterswijk West", code = "Www" },
            new Station { name = "Woerden", code = "Wd" },
            new Station { name = "Wolfheze", code = "Wf" },
            new Station { name = "Wolvega", code = "Wv" },
            new Station { name = "Workum", code = "Wk" },
            new Station { name = "Wormerveer", code = "Wm" },
            new Station { name = "Zaandam Kogerveld", code = "Zdk" },
            new Station { name = "Zaandam", code = "Zd" },
            new Station { name = "Zaandijk Zaanse Schans", code = "Kzd" },
            new Station { name = "Zaltbommel", code = "Zbm" },
            new Station { name = "Zandvoort aan Zee", code = "Zvt" },
            new Station { name = "Zetten-Andelst", code = "Za" },
            new Station { name = "Zevenaar", code = "Zv" },
            new Station { name = "Zevenbergen", code = "Zvb" },
            new Station { name = "Zoetermeer Oost", code = "Ztmo" },
            new Station { name = "Zoetermeer", code = "Ztm" },
            new Station { name = "Zuidbroek", code = "Zb" },
            new Station { name = "Zuidhorn", code = "Zh" },
            new Station { name = "Zutphen", code = "Zp" },
            new Station { name = "Zwijndrecht", code = "Zwd" },
            new Station { name = "Zwolle", code = "Zl" },
            new Station { name = "Zwolle Stadshagen", code = "Zlsh" }
        };

            foreach (var station in stations)
            {
                await Database.InsertAsync(station);
            }
        }
    }
}
